name: Continuous Integration
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-2025
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git mingw-w64-ucrt-x86_64-gcc
          pacboy: >-
            cmake:p
            gtk4:p
            portaudio:p
      - name: CI-Build
        run: |
          cmake --build build --config Debug --target all -j 12
